### ISSUE TITLE
can use to build kernel for Lenovo Legion Pro?

### ISSUE THREAD

**Issue by taotaoafk** [isning/android_kernel_lenovo_sm8250#1]

**Comment by isning** [comment]
This is almost original kernel for TB
-Q706F, I tried to make it working on TB-J716F, but I can't even make touchscreen work.

I guess this won't work well for Legion Y700, but at least It can boot your pad.

**Comment by isning** [comment]
You can give it a try

**Comment by taotaoafk** [comment]
> You can give it a try

Oh, i see, well, i have get the kernel source from lenovo of my phone, but dint boot, im new on android building. Maybe lenovo gave a broken kernel source of legion pro... But thanks for reply, i hope you fix succesfully the kernel
